"""Initialize database with SGI, User, and Review models

Revision ID: e67cef64464f
Revises: 
Create Date: 2026-04-08 14:04:37.281327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e67cef64464f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sgi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=True),
    sa.Column('adresse', sa.String(length=500), nullable=True),
    sa.Column('bp', sa.String(length=100), nullable=True),
    sa.Column('pays', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('fax', sa.String(length=20), nullable=True),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('site_web', sa.String(length=255), nullable=True),
    sa.Column('agrement_crepmf', sa.String(length=100), nullable=True),
    sa.Column('gestion_libre', sa.String(length=50), nullable=True),
    sa.Column('apport_initial_fcfa', sa.String(length=50), nullable=True),
    sa.Column('frais_courtage', sa.String(length=50), nullable=True),
    sa.Column('frais_conservation', sa.String(length=100), nullable=True),
    sa.Column('frais_transfert', sa.String(length=100), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sgi_created_at'), 'sgi', ['created_at'], unique=False)
    op.create_index(op.f('ix_sgi_id'), 'sgi', ['id'], unique=False)
    op.create_index(op.f('ix_sgi_nom'), 'sgi', ['nom'], unique=False)
    op.create_index(op.f('ix_sgi_pays'), 'sgi', ['pays'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sgi_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reviewer_name', sa.String(length=255), nullable=True),
    sa.Column('reviewer_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('moderation_reason', sa.Text(), nullable=True),
    sa.Column('moderated_by', sa.UUID(), nullable=True),
    sa.Column('moderated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['moderated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sgi_id'], ['sgi.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_rating'), 'reviews', ['rating'], unique=False)
    op.create_index(op.f('ix_reviews_sgi_id'), 'reviews', ['sgi_id'], unique=False)
    op.create_index(op.f('ix_reviews_status'), 'reviews', ['status'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_status'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_sgi_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_rating'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sgi_pays'), table_name='sgi')
    op.drop_index(op.f('ix_sgi_nom'), table_name='sgi')
    op.drop_index(op.f('ix_sgi_id'), table_name='sgi')
    op.drop_index(op.f('ix_sgi_created_at'), table_name='sgi')
    op.drop_table('sgi')
    # ### end Alembic commands ###
